name: 🚀 Feature Request
description: Suggest an idea for memreps
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What is your idea?
      description: Describe the feature you would like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful to you or other users?
    validations:
      required: true