// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCuFM07lAzKoWn4rhgc7kbW268J_uanrQ',
    appId: '1:146021442934:web:14e1378b26ef8a86c00657',
    messagingSenderId: '146021442934',
    projectId: 'openclaw-bot-486015',
    authDomain: 'openclaw-bot-486015.firebaseapp.com',
    storageBucket: 'openclaw-bot-486015.firebasestorage.app',
    measurementId: 'G-3SZR0RSXDK',
  );
}
